# Site settings
title: Henrison Hsieh
# email: your-email@domain.com
# description: > # means to ignore newlines until "baseurl:"
description: "Assistant Professor<br>Institute of Linguistics, National Tsing Hua University"
# Previously, I lived in Boston, where I attended Boston University and earned my BA majoring in Linguistics and Computer Science before working at a (now not so) small web startup, Jana Inc.
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
last_updated: August 2024
# twitter_username: jekyllrb
github_username:  henrison

# Build settings
markdown: kramdown
# Theme page: https://github.com/<remote_theme>
remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: mmistakes/minimal-mistakes@4.26.2
plugins:
  # - jekyll-include-cache # used with minimal-mistakes
  - jekyll-remote-theme
  - jekyll-feed
